# Generated by Django 3.1 on 2020-08-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panglist',
            fields=[
                ('pangnum', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pangname', models.CharField(max_length=30)),
                ('pangcate', models.CharField(max_length=20)),
                ('pangimg', models.FileField(blank=True, upload_to='post_image')),
                ('pangcount', models.IntegerField()),
                ('panginfo', models.CharField(max_length=1000)),
                ('pangal', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Panglists',
            },
        ),
        migrations.CreateModel(
            name='Pangstore',
            fields=[
                ('stonum', models.IntegerField(primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('stoname', models.CharField(max_length=30)),
                ('stoadd', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Pangstores',
            },
        ),
        migrations.CreateModel(
            name='Panguser',
            fields=[
                ('usernum', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pw', models.CharField(max_length=20)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pang.panglist')),
            ],
            options={
                'verbose_name_plural': 'Pangusers',
            },
        ),
        migrations.AddField(
            model_name='panglist',
            name='stonum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pang.pangstore'),
        ),
    ]
