# Generated by Django 3.1 on 2020-08-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panglist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pangstore',
            options={},
        ),
        migrations.AlterModelOptions(
            name='panguser',
            options={},
        ),
        migrations.AlterField(
            model_name='panglist',
            name='pangimg',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='panglist',
            name='pangnum',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
